package service

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/mhsanaei/3x-ui/v2/database"
	"github.com/mhsanaei/3x-ui/v2/database/model"
	"github.com/mhsanaei/3x-ui/v2/logger"
	"github.com/mhsanaei/3x-ui/v2/util/json_util"
	"github.com/mhsanaei/3x-ui/v2/xray"
)

const (
	pptpSessionsFile = "/etc/x-ui/pptp-sessions"
	pptpUserMapFile  = "/etc/x-ui/pptp-usermap"
)

// PptpService manages PPTP VPN server configuration including pptpd, pppd,
// and iptables TPROXY rules for routing traffic through Xray.
type PptpService struct {
	inboundService InboundService
	nftService     NftService
}

// pptpSettings represents the PPTP-specific settings stored in the inbound's Settings JSON.
type pptpSettings struct {
	IpRange string       `json:"ipRange"`
	LocalIp string       `json:"localIp"`
	Dns1    string       `json:"dns1"`
	Dns2    string       `json:"dns2"`
	Mtu     int          `json:"mtu"`
	Clients []pptpClient `json:"clients"`
}

type pptpClient struct {
	ID       string `json:"id"`       // PPTP username
	Password string `json:"password"` // PPTP password
	Email    string `json:"email"`    // tracking identifier
	Enable   bool   `json:"enable"`
}

func (s *PptpService) GetPptpInbounds() ([]*model.Inbound, error) {
	db := database.GetDB()
	var inbounds []*model.Inbound
	err := db.Model(model.Inbound{}).Where("protocol = ?", "pptp").Find(&inbounds).Error
	return inbounds, err
}

func (s *PptpService) parseSettings(inbound *model.Inbound) (*pptpSettings, error) {
	settings := &pptpSettings{}
	err := json.Unmarshal([]byte(inbound.Settings), settings)
	return settings, err
}

// GetSubnetForInbound returns 10.1.x where x is derived from the inbound ID.
func (s *PptpService) GetSubnetForInbound(inbound *model.Inbound) string {
	settings, err := s.parseSettings(inbound)
	if err == nil && settings.LocalIp != "" {
		parts := strings.Split(settings.LocalIp, ".")
		if len(parts) >= 3 {
			return strings.Join(parts[:3], ".")
		}
	}
	// Deterministic: 10.1.{id}.0/24
	return fmt.Sprintf("10.1.%d", inbound.Id)
}

// GetTproxyPort returns the TPROXY port for this inbound (shared formula with L2TP).
func (s *PptpService) GetTproxyPort(inbound *model.Inbound) int {
	return 12300 + inbound.Id
}

// GetDokodemoConfig builds a dokodemo-door inbound config for TPROXY capture.
func (s *PptpService) GetDokodemoConfig(inbound *model.Inbound) *xray.InboundConfig {
	port := s.GetTproxyPort(inbound)
	settings := fmt.Sprintf(`{"network":"tcp,udp","followRedirect":true}`)
	streamSettings := `{"sockopt":{"tproxy":"tproxy","mark":255}}`
	sniffing := `{"enabled":true,"destOverride":["http","tls"]}`

	return &xray.InboundConfig{
		Listen:         json_util.RawMessage(`"0.0.0.0"`),
		Port:           port,
		Protocol:       "dokodemo-door",
		Settings:       json_util.RawMessage(settings),
		StreamSettings: json_util.RawMessage(streamSettings),
		Tag:            inbound.Tag,
		Sniffing:       json_util.RawMessage(sniffing),
	}
}

// GenerateAllConfigs regenerates all PPTP-related config files from the database state.
func (s *PptpService) GenerateAllConfigs() error {
	inbounds, err := s.GetPptpInbounds()
	if err != nil {
		return err
	}

	if len(inbounds) == 0 {
		return nil
	}

	if err := s.GeneratePptpdConfig(inbounds); err != nil {
		return err
	}
	if err := s.GenerateChapSecrets(); err != nil {
		return err
	}
	for _, inbound := range inbounds {
		if err := s.GeneratePPPOptions(inbound); err != nil {
			return err
		}
	}

	if err := s.GenerateUserMap(); err != nil {
		return err
	}
	if err := s.GenerateIpUpDown(); err != nil {
		return err
	}

	return nil
}

// GeneratePptpdConfig writes /etc/pptpd.conf with the PPTP inbound settings.
func (s *PptpService) GeneratePptpdConfig(inbounds []*model.Inbound) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by 3x-ui PPTP service\n")

	for _, inbound := range inbounds {
		settings, err := s.parseSettings(inbound)
		if err != nil {
			logger.Warning("PPTP: skipping inbound", inbound.Id, err)
			continue
		}

		subnet := s.GetSubnetForInbound(inbound)
		ipRange := settings.IpRange
		if ipRange == "" {
			ipRange = fmt.Sprintf("%s.10-%s.50", subnet, subnet)
		}
		localIp := settings.LocalIp
		if localIp == "" {
			localIp = fmt.Sprintf("%s.1", subnet)
		}

		b.WriteString(fmt.Sprintf("option /etc/ppp/pptpd-options-%d\n", inbound.Id))
		b.WriteString(fmt.Sprintf("localip %s\n", localIp))
		// pptpd remoteip format: start-end (e.g., 10.1.2.10-50)
		// Parse ipRange which is in format "10.1.2.10-10.1.2.50"
		remoteIp := ipRange
		parts := strings.SplitN(ipRange, "-", 2)
		if len(parts) == 2 {
			endParts := strings.Split(parts[1], ".")
			if len(endParts) == 4 {
				// Full IP on both sides: "10.1.2.10-10.1.2.50" -> "10.1.2.10-50"
				remoteIp = fmt.Sprintf("%s-%s", parts[0], endParts[3])
			}
		}
		b.WriteString(fmt.Sprintf("remoteip %s\n", remoteIp))
	}

	return s.writeFile("/etc/pptpd.conf", b.String())
}

// GeneratePPPOptions writes per-inbound PPP options file for pptpd.
func (s *PptpService) GeneratePPPOptions(inbound *model.Inbound) error {
	settings, err := s.parseSettings(inbound)
	if err != nil {
		return err
	}

	mtu := settings.Mtu
	if mtu == 0 {
		mtu = 1400
	}
	dns1 := settings.Dns1
	if dns1 == "" {
		dns1 = "8.8.8.8"
	}
	dns2 := settings.Dns2
	if dns2 == "" {
		dns2 = "8.8.4.4"
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("name pptp-%d\n", inbound.Id))
	b.WriteString("refuse-pap\n")
	b.WriteString("refuse-chap\n")
	b.WriteString("require-mschap-v2\n")
	b.WriteString("require-mppe\n")
	b.WriteString(fmt.Sprintf("ms-dns %s\n", dns1))
	b.WriteString(fmt.Sprintf("ms-dns %s\n", dns2))
	b.WriteString("proxyarp\n")
	b.WriteString("nodefaultroute\n")
	b.WriteString("lock\n")
	b.WriteString("nologfd\n")
	b.WriteString("lcp-echo-interval 30\n")
	b.WriteString("lcp-echo-failure 4\n")
	b.WriteString(fmt.Sprintf("mtu %d\n", mtu))
	b.WriteString(fmt.Sprintf("mru %d\n", mtu))

	return s.writeFile(fmt.Sprintf("/etc/ppp/pptpd-options-%d", inbound.Id), b.String())
}

// getDisabledEmails returns a set of client emails that are disabled in the
// client_traffics table (due to traffic limit or expiry).
func (s *PptpService) getDisabledEmails() map[string]bool {
	disabled := make(map[string]bool)
	db := database.GetDB()
	var emails []string
	db.Model(&xray.ClientTraffic{}).
		Where("enable = ?", false).
		Pluck("email", &emails)
	for _, e := range emails {
		disabled[e] = true
	}
	return disabled
}

// GenerateChapSecrets writes /etc/ppp/chap-secrets with entries from BOTH PPTP and L2TP inbounds.
// This ensures both protocols coexist in the shared chap-secrets file.
func (s *PptpService) GenerateChapSecrets() error {
	disabledEmails := s.getDisabledEmails()

	var b strings.Builder
	b.WriteString("# Auto-generated by 3x-ui PPP service\n")
	b.WriteString("# client    server       secret       IP\n")

	// Include L2TP inbound clients
	db := database.GetDB()
	var l2tpInbounds []*model.Inbound
	db.Model(model.Inbound{}).Where("protocol = ?", "l2tp").Find(&l2tpInbounds)

	for _, inbound := range l2tpInbounds {
		l2tpS := &l2tpSettings{}
		if err := json.Unmarshal([]byte(inbound.Settings), l2tpS); err != nil {
			continue
		}
		serverName := fmt.Sprintf("l2tp-%d", inbound.Id)
		for _, client := range l2tpS.Clients {
			if !client.Enable || disabledEmails[client.Email] {
				continue
			}
			b.WriteString(fmt.Sprintf("%s    %s    %s    *\n", client.ID, serverName, client.Password))
		}
	}

	// Include PPTP inbound clients
	pptpInbounds, err := s.GetPptpInbounds()
	if err != nil {
		return err
	}

	for _, inbound := range pptpInbounds {
		settings, err := s.parseSettings(inbound)
		if err != nil {
			continue
		}
		serverName := fmt.Sprintf("pptp-%d", inbound.Id)
		for _, client := range settings.Clients {
			if !client.Enable || disabledEmails[client.Email] {
				continue
			}
			b.WriteString(fmt.Sprintf("%s    %s    %s    *\n", client.ID, serverName, client.Password))
		}
	}

	return s.writeFile("/etc/ppp/chap-secrets", b.String())
}

// SetupAllTproxy sets up kernel modules, ip rules, and nftables rules for TPROXY.
func (s *PptpService) SetupAllTproxy() error {
	// Enable IP forwarding
	s.runCmd("sysctl", "-w", "net.ipv4.ip_forward=1")

	// Load kernel modules needed for PPTP
	s.runCmd("modprobe", "nf_conntrack_pptp")
	s.runCmd("modprobe", "ip_gre")
	s.runCmd("modprobe", "ppp_generic")
	s.runCmd("modprobe", "ppp_mppe")
	s.runCmd("modprobe", "nf_tproxy_ipv4")

	// Set up ip rule and route table (check if already exists to avoid duplicates)
	output, _ := exec.Command("ip", "rule", "show").Output()
	if !strings.Contains(string(output), "fwmark 0x1 lookup 100") {
		s.runCmd("ip", "rule", "add", "fwmark", "1", "lookup", "100")
	}
	s.runCmd("ip", "route", "replace", "local", "0.0.0.0/0", "dev", "lo", "table", "100")

	return s.nftService.ApplyNftRules()
}

// RestartServices restarts pptpd.
func (s *PptpService) RestartServices() error {
	inbounds, err := s.GetPptpInbounds()
	if err != nil {
		return err
	}

	if len(inbounds) == 0 {
		return nil
	}

	if err := s.runCmd("systemctl", "restart", "pptpd"); err != nil {
		logger.Warning("PPTP: failed to restart pptpd:", err)
	}

	return nil
}

// InitPptp initializes PPTP services on panel startup.
func (s *PptpService) InitPptp() {
	inbounds, err := s.GetPptpInbounds()
	if err != nil || len(inbounds) == 0 {
		return
	}

	logger.Info("PPTP: initializing PPTP services for", len(inbounds), "inbound(s)")

	s.nftService.CleanupLegacyIptables()

	if err := s.GenerateAllConfigs(); err != nil {
		logger.Warning("PPTP: failed to generate configs:", err)
		return
	}
	if err := s.SetupAllTproxy(); err != nil {
		logger.Warning("PPTP: failed to setup TPROXY:", err)
	}
	if err := s.RestartServices(); err != nil {
		logger.Warning("PPTP: failed to restart services:", err)
	}
}

// GenerateUserMap writes /etc/x-ui/pptp-usermap with username→email mappings.
func (s *PptpService) GenerateUserMap() error {
	inbounds, err := s.GetPptpInbounds()
	if err != nil {
		return err
	}

	disabledEmails := s.getDisabledEmails()

	var b strings.Builder
	for _, inbound := range inbounds {
		settings, err := s.parseSettings(inbound)
		if err != nil {
			continue
		}
		for _, client := range settings.Clients {
			if client.Enable && client.Email != "" && !disabledEmails[client.Email] {
				b.WriteString(fmt.Sprintf("%s %s\n", client.ID, client.Email))
			}
		}
	}

	return s.writeFile(pptpUserMapFile, b.String())
}

// GenerateIpUpDown writes the pppd ip-up.d and ip-down.d scripts for PPTP session tracking.
func (s *PptpService) GenerateIpUpDown() error {
	os.MkdirAll("/etc/ppp/ip-up.d", 0755)
	os.MkdirAll("/etc/ppp/ip-down.d", 0755)

	ipUp := `#!/bin/sh
# Auto-generated by 3x-ui PPTP service — do not edit
IFACE="$1"
REMOTE_IP="$5"
USERNAME="$PEERNAME"

[ -z "$USERNAME" ] && exit 0
[ -z "$REMOTE_IP" ] && exit 0

# Look up email from usermap — exit if user is not a PPTP client
USERMAP="` + pptpUserMapFile + `"
[ ! -f "$USERMAP" ] && exit 0
EMAIL=$(awk -v u="$USERNAME" '$1 == u {print $2; exit}' "$USERMAP")
[ -z "$EMAIL" ] && exit 0

# Record session: email IP interface
SESSIONS="` + pptpSessionsFile + `"
grep -v " $REMOTE_IP " "$SESSIONS" 2>/dev/null > "$SESSIONS.tmp" || true
echo "$EMAIL $REMOTE_IP $IFACE" >> "$SESSIONS.tmp"
mv "$SESSIONS.tmp" "$SESSIONS"

# Add nft counters and accounting rules
COUNTER_IP=$(echo "$REMOTE_IP" | tr '.' '_')
nft add counter ip vpn "pptp_up_${COUNTER_IP}" 2>/dev/null
nft add counter ip vpn "pptp_down_${COUNTER_IP}" 2>/dev/null
if ! nft list chain ip vpn pptp_acct 2>/dev/null | grep -q "addr ${REMOTE_IP} "; then
    nft add rule ip vpn pptp_acct ip saddr "$REMOTE_IP" counter name "pptp_up_${COUNTER_IP}"
    nft add rule ip vpn pptp_acct ip daddr "$REMOTE_IP" counter name "pptp_down_${COUNTER_IP}"
fi
`

	ipDown := `#!/bin/sh
# Auto-generated by 3x-ui PPTP service — do not edit
REMOTE_IP="$5"

[ -z "$REMOTE_IP" ] && exit 0

# Only process if this IP is in PPTP sessions
SESSIONS="` + pptpSessionsFile + `"
[ ! -f "$SESSIONS" ] && exit 0
grep -q " $REMOTE_IP " "$SESSIONS" || exit 0

# Remove session entry
grep -v " $REMOTE_IP " "$SESSIONS" > "$SESSIONS.tmp" || true
mv "$SESSIONS.tmp" "$SESSIONS"

# Remove nft accounting rules and counters
COUNTER_IP=$(echo "$REMOTE_IP" | tr '.' '_')
nft -a list chain ip vpn pptp_acct 2>/dev/null | grep "addr ${REMOTE_IP} " | while IFS= read -r line; do
    handle=$(echo "$line" | sed -n 's/.*# handle \([0-9]*\).*/\1/p')
    [ -n "$handle" ] && nft delete rule ip vpn pptp_acct handle "$handle" 2>/dev/null
done
nft delete counter ip vpn "pptp_up_${COUNTER_IP}" 2>/dev/null
nft delete counter ip vpn "pptp_down_${COUNTER_IP}" 2>/dev/null
`

	if err := s.writeFileMode("/etc/ppp/ip-up.d/pptp-acct", ipUp, 0755); err != nil {
		return err
	}
	return s.writeFileMode("/etc/ppp/ip-down.d/pptp-acct", ipDown, 0755)
}

type pptpSession struct {
	Email     string
	IP        string
	Interface string
}

func (s *PptpService) readSessionList() []pptpSession {
	data, err := os.ReadFile(pptpSessionsFile)
	if err != nil {
		return nil
	}

	var sessions []pptpSession
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		fields := strings.Fields(strings.TrimSpace(scanner.Text()))
		if len(fields) >= 3 {
			sessions = append(sessions, pptpSession{
				Email:     fields[0],
				IP:        fields[1],
				Interface: fields[2],
			})
		}
	}
	return sessions
}

func (s *PptpService) readSessions() map[string]string {
	sessions := make(map[string]string)
	for _, sess := range s.readSessionList() {
		sessions[sess.Email] = sess.IP
	}
	return sessions
}

// KillDisabledSessions kills active PPP sessions for clients that are no longer
// allowed to connect (disabled in settings or disabled in client_traffics).
func (s *PptpService) KillDisabledSessions() {
	inbounds, err := s.GetPptpInbounds()
	if err != nil {
		return
	}
	disabledEmails := s.getDisabledEmails()

	allowed := make(map[string]bool)
	for _, inbound := range inbounds {
		settings, err := s.parseSettings(inbound)
		if err != nil {
			continue
		}
		for _, client := range settings.Clients {
			if client.Enable && !disabledEmails[client.Email] {
				allowed[client.Email] = true
			}
		}
	}

	for _, sess := range s.readSessionList() {
		if !allowed[sess.Email] && sess.Interface != "" {
			pidFile := fmt.Sprintf("/var/run/%s.pid", sess.Interface)
			pidData, err := os.ReadFile(pidFile)
			if err == nil {
				pid := strings.TrimSpace(string(pidData))
				if pid != "" {
					s.runCmd("kill", pid)
					logger.Infof("PPTP: killed disabled session %s (email=%s, ip=%s)", sess.Interface, sess.Email, sess.IP)
				}
			}
		}
	}
}

// DisableClients enforces limits for the given client emails.
func (s *PptpService) DisableClients(emails []string) {
	if len(emails) == 0 {
		return
	}

	emailSet := make(map[string]bool, len(emails))
	for _, e := range emails {
		emailSet[e] = true
	}

	for _, sess := range s.readSessionList() {
		if emailSet[sess.Email] && sess.Interface != "" {
			pidFile := fmt.Sprintf("/var/run/%s.pid", sess.Interface)
			pidData, err := os.ReadFile(pidFile)
			if err == nil {
				pid := strings.TrimSpace(string(pidData))
				if pid != "" {
					s.runCmd("kill", pid)
					logger.Infof("PPTP: killed session %s (email=%s, ip=%s)", sess.Interface, sess.Email, sess.IP)
				}
			}
		}
	}

	if err := s.GenerateChapSecrets(); err != nil {
		logger.Warning("PPTP: failed to regenerate chap-secrets:", err)
	}
	if err := s.GenerateUserMap(); err != nil {
		logger.Warning("PPTP: failed to regenerate usermap:", err)
	}
}

func (s *PptpService) writeFile(path, content string) error {
	return s.writeFileMode(path, content, 0644)
}

func (s *PptpService) writeFileMode(path, content string, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), mode); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	return nil
}

func (s *PptpService) runCmd(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		logger.Debugf("PPTP: cmd '%s %s' failed: %s %v", name, strings.Join(args, " "), string(output), err)
		return err
	}
	return nil
}
